title: "Academic Incentive Ontology: A Model of Blockchain-Based Data Sharing"

#setup
url:          https://sharing-science.github.io/
baseurl:      https://sharing-science.github.io/academic-incentive-ontology


author:
name:         'Kacy Adams'


github:
  repo:       https://github.com/sharing-science/academic-incentive-ontology/
